# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 02:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('employ_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Employ ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10, verbose_name='the record of action')),
                ('login_id', models.CharField(max_length=10, verbose_name='the owner of action')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='the date of action')),
                ('worker', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='leave starts on')),
                ('end_date', models.DateTimeField(verbose_name='leave ends on')),
                ('leave_type', models.CharField(choices=[('AN', 'Annual Leave'), ('FL', 'Floating Holiday'), ('CO', 'Compensated Leave'), ('OF', 'Official Leave'), ('PE', 'Personal Leave'), ('PA', 'Parental Leave'), ('SI', 'Sick Leave'), ('ME', 'Menstrual Leave'), ('MA', 'Marital Leave'), ('FU', 'Funeral Leave'), ('BI', 'Birthday Leave'), ('NO', 'NoPay Leave'), ('RE', 'Rearrange')], max_length=2)),
                ('deputy', models.CharField(max_length=20, verbose_name='responsibility goes to')),
                ('login_id', models.CharField(max_length=10, verbose_name='who sent this leave application')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='the date when this leave application sent')),
                ('worker', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='work starts on')),
                ('end_date', models.DateTimeField(verbose_name='work ends on')),
                ('shift_type', models.CharField(choices=[('NT', 'Night'), ('DY', 'Day'), ('SG', 'Swing')], max_length=2, unique_for_date='start_date')),
                ('title', models.CharField(default='', max_length=12)),
                ('login_id', models.CharField(max_length=10, verbose_name='the owner of creation or update')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='the date of creation')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='the date of update')),
                ('worker', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('worker', 'start_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='leave',
            unique_together=set([('worker', 'start_date')]),
        ),
    ]
